AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # API Gateway
  ApiGatewayRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: ApiRestEventos
      Description: 'API Gateway para gestionar eventos'

  # Recurso "/eventos"
  EventosResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId  # Hace referencia al recurso raíz
      PathPart: "eventos"  # Define la ruta como "/eventos"
      RestApiId: !Ref ApiGatewayRestApi
  
  # Recurso "/asistentes"
  AsistentesResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId  # Hace referencia al recurso raíz
      PathPart: "asistentes"  # Define la ruta como "/eventos"
      RestApiId: !Ref ApiGatewayRestApi

  # # Método POST en "/eventos"
  # PostMethodForEventos:
  #   Type: 'AWS::ApiGateway::Method'
  #   Properties:
  #     AuthorizationType: CUSTOM  # Tipo de autorización personalizada usando Lambda Authorizer
  #     AuthorizerId: !Ref ApiGatewayAuthorizer  # Importa el AuthorizerId
  #     HttpMethod: POST
  #     ResourceId: !Ref EventosResource
  #     RestApiId: !Ref ApiGatewayRestApi
  #     Integration:
  #       IntegrationHttpMethod: POST
  #       Type: AWS_PROXY
  #       Uri: !Sub
  #         arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${!ImportValue LambdaFunctionArn}/invocations
