AWSTemplateFormatVersion: "2010-09-09"

Description: "Stack Anidado"

Resources:
  LambdasDynamoEvents:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://udem-lambda-code.s3.us-east-1.amazonaws.com/stack-lambdas-DynamoDB-events.yml"

  AttendeeRegistersStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://udem-lambda-code.s3.us-east-1.amazonaws.com/stack-attendee-register.yml"
      Parameters:
        EventsTableArn: !GetAtt LambdasDynamoEvents.Outputs.EventsTableArn
        EventsTableName: !GetAtt LambdasDynamoEvents.Outputs.EventsTableName
    DependsOn: LambdasDynamoEvents

  APIGatewayAuthorizerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://udem-lambda-code.s3.us-east-1.amazonaws.com/stack-api-gateway.yml"
      Parameters:
        LambdaCreateEventFunctionArn: !GetAtt LambdasDynamoEvents.Outputs.LambdaCreateEventFunctionArn
        LambdaEditEventFunctionArn: !GetAtt LambdasDynamoEvents.Outputs.LambdaEditEventFunctionArn
        LambdaDeleteEventFunctionArn: !GetAtt LambdasDynamoEvents.Outputs.LambdaDeleteEventFunctionArn
        LambdaViewEventFunctionArn: !GetAtt LambdasDynamoEvents.Outputs.LambdaViewEventFunctionArn
        AttendeeRegisterLambdaArn: !GetAtt AttendeeRegistersStack.Outputs.AttendeeRegisterLambdaArn
    DependsOn: AttendeeRegistersStack
