AWSTemplateFormatVersion: "2010-09-09"

Description: "Stack Anidado"

Resources:
  LambdasDynamoEvents:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ""

  AttendeeRegistersStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ""
      Parameters:
        EventsTableArn: !GetAtt LambdasDynamoEvents.Outputs.EventsTableArn
        EventsTableName: !GetAtt LambdasDynamoEvents.Outputs.EventsTableName
    DependsOn: LambdasDynamoEvents
