AWSTemplateFormatVersion: "2010-09-09"

Description: Template para crear una instancia de Amazon Lightsail con acceso SSH.

Parameters:
  InstanceName:
    Type: String

  ApiBaseURL:
    Type: String

Resources:
  MyLightsailInstance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: !Ref InstanceName
      AvailabilityZone: us-east-1a # Cambia según tu región preferida
      BlueprintId: ubuntu_24_04 # Puedes cambiar a otra imagen según sea necesario
      BundleId: micro_3_0 # Cambia según el tamaño que necesites
      UserData:
        Fn::Join:
          - ""
          - - "#!/bin/bash\n"
            - "sudo apt-get update\n"
            - "sudo apt-get install -y docker.io docker-compose\n"
            - "sudo systemctl start docker\n"
            - "sudo systemctl enable docker\n"
            - "git clone https://github.com/rafredyramirez/FrontEventosAWS.git\n"
            - "cd FrontEventosAWS/\n"
            - "cd my_project/\n"
            # - "git clone https://github.com/faberrocalv/django-serverless.git\n"
            # - "cd django-serverless/\n"
            - "my_ip=$(curl http://checkip.amazonaws.com)\n"
            - "echo \"INSTANCE_IP=${my_ip}\" > .env\n"
            - 'echo "API_GATEWAY_BASE='
            - !Ref ApiBaseURL
            - "\" >> .env\n"
            - python manage.py runserver 0.0.0.0:8000
            - "sudo docker-compose up -d\n"

Outputs:
  InstanceId:
    Description: ID de la instancia de Lightsail.
    Value: !Ref MyLightsailInstance
